"""make place nullable

Revision ID: 320e3fa9239a
Revises: c63a51f76df0
Create Date: 2025-03-22 18:01:03.556222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '320e3fa9239a'
down_revision: Union[str, None] = 'c63a51f76df0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'place',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'photo_URL',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'photo_URL',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'place',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
