"""вторая попытка

Revision ID: 510be897d6d5
Revises: 2549b886e224
Create Date: 2025-04-02 17:20:32.902685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '510be897d6d5'
down_revision: Union[str, None] = '2549b886e224'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login', sa.String(), nullable=False))
    op.drop_constraint('users_phone_number_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['login'])
    op.drop_column('users', 'description')
    op.drop_column('users', 'place')
    op.drop_column('users', 'user_name')
    op.drop_column('users', 'photo_URL')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('photo_URL', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('place', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_phone_number_key', 'users', ['phone_number'])
    op.drop_column('users', 'login')
    # ### end Alembic commands ###
