"""changing role names

Revision ID: d122e8790218
Revises: e726d35571ff
Create Date: 2025-04-18 18:27:47.766415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd122e8790218'
down_revision: Union[str, None] = 'e726d35571ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('users', sa.Column('premium', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('tester', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('admin', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('content_manager', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('system_analyst', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_column('users', 'is_system_analyst')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'is_premium_user')
    op.drop_column('users', 'is_content_manager')
    op.drop_column('users', 'is_user')
    op.drop_column('users', 'is_tester')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_tester', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_user', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_content_manager', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_premium_user', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_system_analyst', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('users', 'system_analyst')
    op.drop_column('users', 'content_manager')
    op.drop_column('users', 'admin')
    op.drop_column('users', 'tester')
    op.drop_column('users', 'premium')
    op.drop_column('users', 'user')
    # ### end Alembic commands ###
