"""hangfing user roles

Revision ID: e726d35571ff
Revises: 510be897d6d5
Create Date: 2025-04-07 18:30:00.870022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e726d35571ff'
down_revision: Union[str, None] = '510be897d6d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_content_manager', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('is_system_analyst', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_column('users', 'is_censor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_censor', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('users', 'is_system_analyst')
    op.drop_column('users', 'is_content_manager')
    # ### end Alembic commands ###
